### ISSUE TITLE
[BUG]小程序莫名一直出现程序错误

### ISSUE THREAD

**Issue by tuanji** [Dreace/NUC-Information#10]
**描述一下你遇到问题
[刚打开提示需要登录，可是账号没问题，课表成绩查询提示程序错误，重新登录后任然提示程序错误,后来提示变成英文的请求失败，体测成绩和班级课表也不可以查了，现在干脆什么也加载不出来]

**截屏**
小程序截屏：
![Screenshot_20210302_095131_com tencent mm](https://user-images.githubusercontent.com/79882421/109585229-0f4faa00-7b3e-11eb-9da9-0bfc3590a192.jpg)

![Screenshot_20210302_100943_com tencent mm](https://user-images.githubusercontent.com/79882421/109586029-7ae64700-7b3f-11eb-8b80-1b5b95e2556b.jpg)

**设备信息**
 - 设备: [e.g. HONOR V30 pro]
 - 系统: [e.g. Andriod 10]
 - 微信版本 [e.g. 8.0.1]
 - 小程序版本 [e.g. 2.3.3]

**Comment by Dreace** [comment]
查课表高峰时期，小程序服务器到学校网络带宽有限，可能会造成网络请求超时，请稍后重试。

**Comment by tuanji** [comment]
> 查课表高峰时期，小程序服务器到学校网络带宽有限，可能会造成网络请求超时，请稍后重试。

服务器错误
![Screenshot_20210302_110359_com tencent mm](https://user-images.githubusercontent.com/79882421/109590843-a2411200-7b47-11eb-9bc3-440973c7981c.jpg)
![Screenshot_20210302_110343_com tencent mm](https://user-images.githubusercontent.com/79882421/109590849-a40ad580-7b47-11eb-9a88-0605e315f854.jpg)
