### ISSUE TITLE
[添加功能]添加老生查询服务

### ISSUE THREAD

**Issue by chichuyun** [Dreace/NUC-Information#6]
博士出国之类的很多事，需要知道本科的成绩或者是绩点，老生似乎不能用VPN访问
在这个小程序中能登陆，但是成绩那一栏都是空白的，是不是因为没有数据造成的

**Comment by Dreace** [comment]
你好，这个学期已经启用新的教务系统，目前微信平台的小程序已经适配为新系统的接口，可能已毕业同学的信息未迁移。QQ 平台的小程序（中北信息）仍支持旧版教务系统，可以尝试查询。





------------------ 原始邮件 ------------------
发件人: chichuyun <notifications@github.com&gt;
发送时间: 2020年2月19日 14:33
收件人: Dreace/NUC-Information <NUC-Information@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[Dreace/NUC-Information] [添加功能]添加老生查询服务 (#6)

**Comment by chichuyun** [comment]
谢谢，我试了QQ的，那个密码好像不是我原来的密码了，也登录不上了，放弃了
